title: Front-end-development
author: Mirakay97
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first blog on Github. I this blog i am going to write about fron-end development, create my first repository and share my contributions to you.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
